Dynamic version of previous code

In [4]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

In [5]:
layers_op = []
for n_weight, n_bias in zip(weights, biases):
    neuron_op = 0
    for n_ip, weight in zip(inputs, n_weight):
        neuron_op += n_ip*weight
    neuron_op += n_bias
    layers_op.append(neuron_op)

In [6]:
layers_op

[4.8, 1.21, 2.385]

### Using NUMPY

In [3]:
import numpy as np

In [8]:
op = np.dot(inputs, weights)##doesnt work

ValueError: shapes (4,) and (3,4) not aligned: 4 (dim 0) != 3 (dim 0)

In [9]:
op = np.dot(weights, inputs)

In [12]:
op = op+biases

In [13]:
op

array([4.8  , 1.21 , 2.385])

### batches, layers and objects

In [8]:
inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

In [9]:
weights = np.array(weights)

In [10]:
inputs = np.array(inputs)

In [14]:
op = np.dot(inputs, weights.T) + biases

#### Transpose weights to do dot product

In [15]:
op

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [17]:
op += biases

In [18]:
op

array([[ 6.8  ,  4.21 ,  2.885],
       [10.9  ,  1.19 ,  0.7  ],
       [ 3.41 ,  4.051,  0.526]])

#### More layerrss

In [20]:
weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

In [23]:
layer1_op = np.dot(inputs, np.array(weights).T) + biases
layer2_op = np.dot(layer1_op, np.array(weights2).T) + biases2

In [24]:
layer1_op

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [25]:
layer2_op

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])

### go to next notebook